---
- hosts: all
  sudo: yes
  tasks:
  - name: Canary App Container
    docker:
      name: canary
      image: 52.33.241.189:5000/direwolf:canary
      state: reloaded
      pull: always
      expose: 3000
      ports:
         - "3000:3000"
