---
- hosts: all
  sudo: yes
  tasks:
  - name: Canary App Container
    docker:
      name: canary
      image: 52.33.151.4:5000/direwolf:canary
      state: reloaded
      pull: always
      ports:
      - "3010:3000"
