jenkins:
   image: mpancha/jenkins
   ports:
     - 8080:8080
     - 50000:50000
   volumes:
     - "/var/jenkins_home:/var/jenkins_home"
   restart: always
registry:
   image: registry:2
   ports:
    - 5000:5000
redis:
   image: redis
   ports:
    - 6379:6379
