---
-  hosts: all
   sudo: yes
   roles:
       - role: angstwad.docker_ubuntu
         ssh_port: 2222
         kernel_package_state: present
         docker_opts: "--insecure-registry 52.34.133.147:5000"
       - { role: crushlovely.newrelic, newrelic_license_key: ce741e53258eb96740dbe5a2ada8074e0d704712 }
   post_tasks:	
       - copy: src=./nrsysmond.cfg dest=/etc/newrelic/nrsysmond.cfg owner=root group=newrelic mode=0644
       - command: service newrelic-sysmond restart
